/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber'

export function Awp_Model_Hunaya(props) {
  const { nodes, materials } = useGLTF('/awp_hunaya.glb')

  const model_ref = useRef();

  useFrame(() => {
    model_ref.current.rotation.y +=0.01;
  })
  return (
    <group ref={model_ref} {...props} dispose={null}>
      <group position={[-1.32, -6.39, -20.32]}>
        <mesh geometry={nodes.Mesh004.geometry} material={materials.awp} />
        <mesh geometry={nodes.Mesh004_1.geometry} material={materials.scope_awp} />
      </group>
    </group>
  )
}

useGLTF.preload('/awp_hunaya.glb')
