/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function M4_nightmare(props) {
  const { nodes, materials } = useGLTF('/M4_NM.glb')

  const model_ref = useRef();

  useFrame(() => {
    model_ref.current.rotation.y +=0.01;
  })
  return (
    <group ref={model_ref} {...props} dispose={null}>
      <mesh geometry={nodes.v_rif_m4a1_s_body3_model0.geometry} material={materials.rif_m4a1_s} position={[3.65, 4.39, -10.04]} />
      <mesh geometry={nodes.v_rif_m4a1_s.geometry} material={materials.rif_m4a1_s} position={[3.65, 4.39, -10.04]} />
      <mesh geometry={nodes.v_rif_m4a1_s_silencer.geometry} material={materials.rif_m4a1_s} position={[3.65, 4.39, -10.04]} />
    </group>
  )
}

useGLTF.preload('/M4_NM.glb')
