/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef,useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

import Tex1 from './assets/textures/aug_birds.png'

export default function Plain_Aug(props) {
  const { scene, nodes, materials } = useGLTF('/Plane_Aug.glb')

  const model_ref = useRef();

  useFrame(() => {
    model_ref.current.rotation.y +=0.01;
  })

  // useLayoutEffect(() => { 
  //   Object.assign(materials.Material, {  
  //     map: colorMap, 
  //     color: currentColor}) 
  // }, [scene, nodes, materials, currentColor, colorMap]); 
 
  return (
    
    <group ref={model_ref} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh.geometry} material={materials.rif_aug} />
      <mesh geometry={nodes.Mesh_1.geometry} material={materials.scope_aug} />
      <mesh geometry={nodes.Mesh_2.geometry} material={materials.rif_aug_scope} />
      <mesh geometry={nodes.Mesh_3.geometry} material={materials.scope_lens_dirt} />
      <mesh geometry={nodes.Mesh_4.geometry} material={materials.rif_aug_scope_glass} />
    </group>
  )
}

useGLTF.preload('/Plane_Aug.glb')
